CREATE TABLE IF NOT EXISTS lecturers (
    lecturer_id VARCHAR(50) PRIMARY KEY,
    staff_number VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    title ENUM('Dr.', 'Prof.', 'Mr.', 'Mrs.', 'Ms.', 'Mx.') NOT NULL,
    primary_department_id VARCHAR(50),
    date_of_birth DATE,
      gender ENUM('Male', 'Female', 'Other') NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    office_location VARCHAR(100),
    employment_status ENUM('full-time', 'part-time', 'visiting', 'emeritus') NOT NULL,
    position_title VARCHAR(100),
    date_joined DATE NOT NULL,
    contract_end_date DATE,
    research_interests TEXT,
    bio TEXT,
    profile_picture_url VARCHAR(255),
    status ENUM('active', 'on_leave', 'sabbatical', 'retired', 'resigned') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
